### ISSUE TITLE
Decompression error in 2011 zipfile

### ISSUE THREAD

**Issue by sh0416** [ckzbullbullet/NICE#2]
Hi,

I encountered error when decompressing zip file started with 2011.

How do I handle this issue?

FYI, the zip file started with 2012 has no errors.

Thanks,
<img width="568" alt="image" src="https://user-images.githubusercontent.com/12251974/155272705-2292e971-bfd5-4989-b4d6-7143072429ad.png">

**Comment by ckzbullbullet** [comment]
Hi,

As this work was done during my internship, I currently did not have time to maintain this repo right now. You can check the official dataset website to
